// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Topic         string             `json:"topic"`
	Payload       []byte             `json:"payload"`
	CreatedAt     time.Time          `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	TraceID       pgtype.Text        `json:"trace_id"`
	AttemptCount  int32              `json:"attempt_count"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	LastError     pgtype.Text        `json:"last_error"`
}
