// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimPendingOutboxEvents(ctx context.Context, arg ClaimPendingOutboxEventsParams) ([]OutboxEvent, error)
	// The outbox queries are the standard cross-service set (same shape as
	// expense's): the router inserts inside its single transaction, the worker
	// claims with SKIP LOCKED and marks published or failed.
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	DeletePublishedOutboxEvents(ctx context.Context) (int64, error)
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
	ReleaseOutboxEventLock(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
