// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ocr/gateway/v1/gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentGateway_SubmitDocument_FullMethodName = "/ocr.gateway.v1.DocumentGateway/SubmitDocument"
	DocumentGateway_GetDocument_FullMethodName    = "/ocr.gateway.v1.DocumentGateway/GetDocument"
)

// DocumentGatewayClient is the client API for DocumentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DocumentGateway is Kontrak A: the public surface business services (expense,
// HR, ...) call to use OCR. Source of truth: docs/reference/api-ocr-gateway.md.
//
// The gateway is a provider-blind concierge: it authenticates the caller
// (per-service API key), rate-limits per caller, maps doc_type -> schema_id,
// and forwards to the ocr engine (Kontrak B) - the payload is never altered.
// Submit is async: the caller receives document_id + QUEUED only; results
// travel back via Kafka topics ocr.document.routed.<service>.v1.
type DocumentGatewayClient interface {
	// Async - balik job reference, bukan hasil. Pembacaan dilakukan ocr di belakang.
	SubmitDocument(ctx context.Context, in *SubmitDocumentRequest, opts ...grpc.CallOption) (*SubmitDocumentResponse, error)
	// Untuk polling client dan reconciliation sweep (event Kafka tidak kunjung sampai).
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
}

type documentGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentGatewayClient(cc grpc.ClientConnInterface) DocumentGatewayClient {
	return &documentGatewayClient{cc}
}

func (c *documentGatewayClient) SubmitDocument(ctx context.Context, in *SubmitDocumentRequest, opts ...grpc.CallOption) (*SubmitDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentGateway_SubmitDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentGatewayClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentGateway_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentGatewayServer is the server API for DocumentGateway service.
// All implementations must embed UnimplementedDocumentGatewayServer
// for forward compatibility.
//
// DocumentGateway is Kontrak A: the public surface business services (expense,
// HR, ...) call to use OCR. Source of truth: docs/reference/api-ocr-gateway.md.
//
// The gateway is a provider-blind concierge: it authenticates the caller
// (per-service API key), rate-limits per caller, maps doc_type -> schema_id,
// and forwards to the ocr engine (Kontrak B) - the payload is never altered.
// Submit is async: the caller receives document_id + QUEUED only; results
// travel back via Kafka topics ocr.document.routed.<service>.v1.
type DocumentGatewayServer interface {
	// Async - balik job reference, bukan hasil. Pembacaan dilakukan ocr di belakang.
	SubmitDocument(context.Context, *SubmitDocumentRequest) (*SubmitDocumentResponse, error)
	// Untuk polling client dan reconciliation sweep (event Kafka tidak kunjung sampai).
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	mustEmbedUnimplementedDocumentGatewayServer()
}

// UnimplementedDocumentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentGatewayServer struct{}

func (UnimplementedDocumentGatewayServer) SubmitDocument(context.Context, *SubmitDocumentRequest) (*SubmitDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDocument not implemented")
}
func (UnimplementedDocumentGatewayServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedDocumentGatewayServer) mustEmbedUnimplementedDocumentGatewayServer() {}
func (UnimplementedDocumentGatewayServer) testEmbeddedByValue()                         {}

// UnsafeDocumentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentGatewayServer will
// result in compilation errors.
type UnsafeDocumentGatewayServer interface {
	mustEmbedUnimplementedDocumentGatewayServer()
}

func RegisterDocumentGatewayServer(s grpc.ServiceRegistrar, srv DocumentGatewayServer) {
	// If the following call panics, it indicates UnimplementedDocumentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentGateway_ServiceDesc, srv)
}

func _DocumentGateway_SubmitDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentGatewayServer).SubmitDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentGateway_SubmitDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentGatewayServer).SubmitDocument(ctx, req.(*SubmitDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentGateway_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentGatewayServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentGateway_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentGatewayServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentGateway_ServiceDesc is the grpc.ServiceDesc for DocumentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocr.gateway.v1.DocumentGateway",
	HandlerType: (*DocumentGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitDocument",
			Handler:    _DocumentGateway_SubmitDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _DocumentGateway_GetDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocr/gateway/v1/gateway.proto",
}
